"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");
const { CAPABILITY_MANIFESTS, validateCapabilityManifest } = require("../packages/capability-manifests");
const {
  generatedCatalogFiles,
  sourceCatalogFromManifests,
  verifyGeneratedCatalogs
} = require("../scripts/generate-capability-catalogs");

const root = path.resolve(__dirname, "..");

test("capability module sources are derived from signed manifests", () => {
  const catalog = sourceCatalogFromManifests();
  assert.deepEqual(catalog.local.map((entry) => entry.capability), ["image-to-editable", "ppt-create", "ppt-improve", "ppt-quality", "project-audit"]);
  assert.deepEqual(catalog.direct.map((entry) => entry.capability), ["siyuan-note"]);
  assert.equal(catalog.local[0].packageName, "@common-tools/slideclone-core");
  assert.deepEqual(CAPABILITY_MANIFESTS.get("image-to-editable").moduleSource, {
    packageName: catalog.local[0].packageName,
    requirePath: catalog.local[0].requirePath,
    exportName: catalog.local[0].exportName
  });
  const manifest = JSON.parse(fs.readFileSync(path.join(root, "packages", "capability-manifests", "image-to-editable", "capability.manifest.json"), "utf8"));
  assert.throws(() => validateCapabilityManifest({ ...manifest, moduleSource: { ...manifest.moduleSource, requirePath: "../../escape" } }), /module source is invalid/);
  assert.throws(() => sourceCatalogFromManifests(new Map([
    ["first", { capability: "first", requiredWorkerProfile: "base", moduleSource: { packageName: "@common-tools/one", requirePath: "../one", exportName: "CAPABILITY_MODULE" } }],
    ["second", { capability: "second", requiredWorkerProfile: "base", moduleSource: { packageName: "@common-tools/one", requirePath: "../two", exportName: "CAPABILITY_MODULE" } }]
  ])), /duplicate packageName/);
  assert.throws(() => sourceCatalogFromManifests(new Map([
    ["direct", { capability: "direct", requiredWorkerProfile: "direct", moduleSource: { packageName: "@common-tools/direct-core", requirePath: "../direct-core", exportName: "CAPABILITY_MODULE" } }]
  ])), /must export REMOTE_CAPABILITY_MODULE/);
  assert.throws(() => sourceCatalogFromManifests(new Map([
    ["local", { capability: "local", requiredWorkerProfile: "base", moduleSource: { packageName: "@common-tools/local-core", requirePath: "../local-core", exportName: "REMOTE_CAPABILITY_MODULE" } }]
  ])), /must export CAPABILITY_MODULE/);
});

test("capability catalogs are generated from manifest-owned module sources", () => {
  assert.equal(verifyGeneratedCatalogs(), true);
  for (const file of generatedCatalogFiles()) {
    const relative = path.relative(root, file.path).replaceAll("\\", "/");
    assert.match(fs.readFileSync(file.path, "utf8"), /Generated by scripts\/generate-capability-catalogs\.js/);
    assert.ok(["packages/capability-registry/local-capability-catalog.js", "packages/remote-mcp-server/direct-capability-catalog.js"].includes(relative));
  }
});
