"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");
const {
  generatedCatalogFiles,
  validateSourceCatalog,
  verifyGeneratedCatalogs
} = require("../scripts/generate-capability-catalogs");

const root = path.resolve(__dirname, "..");

test("capability module source catalog validates local and direct owners", () => {
  const source = JSON.parse(fs.readFileSync(path.join(root, "packages", "capability-manifests", "capability-module-sources.json"), "utf8"));
  const catalog = validateSourceCatalog(source);
  assert.deepEqual(catalog.local.map((entry) => entry.capability), ["image-to-editable", "project-audit", "ppt-quality", "ppt-improve", "ppt-create"]);
  assert.deepEqual(catalog.direct.map((entry) => entry.capability), ["siyuan-note"]);
  assert.throws(() => validateSourceCatalog({ ...source, local: [...source.local, source.local[0]] }), /duplicate capability/);
  assert.throws(() => validateSourceCatalog({ ...source, direct: [{ ...source.direct[0], requirePath: "../../escape" }] }), /requirePath is invalid/);
});

test("capability catalogs are generated from capability module sources", () => {
  assert.equal(verifyGeneratedCatalogs(), true);
  for (const file of generatedCatalogFiles()) {
    const relative = path.relative(root, file.path).replaceAll("\\", "/");
    assert.match(fs.readFileSync(file.path, "utf8"), /Generated by scripts\/generate-capability-catalogs\.js/);
    assert.ok(["packages/capability-registry/local-capability-catalog.js", "packages/remote-mcp-server/direct-capability-catalog.js"].includes(relative));
  }
});
