"use strict";
const test = require("node:test");
const assert = require("node:assert/strict");
const { fitSourceBorders } = require("../packages/slideclone-core/source-border-fit");

function image(w = 120, h = 80) { return { width: w, height: h, rgba: new Uint8Array(w * h * 4).fill(255) }; }
function pixel(im, x, y, color) { const i = (y * im.width + x) * 4; im.rgba.set([...color, 255], i); }
function frame(im, x, y, w, h, color = [91, 163, 234]) { for (let xx = x; xx <= x + w; xx += 1) { pixel(im, xx, y, color); pixel(im, xx, y + h, color); } for (let yy = y; yy <= y + h; yy += 1) { pixel(im, x, yy, color); pixel(im, x + w, yy, color); } }
function node(box = { x: 22, y: 18, w: 46, h: 30 }) { return { type: "roundRect", box, style: { stroke: "#1473E6" }, source: { nativeComponentRole: "node", semanticNativeStructure: true } }; }
function run(im, shapes = [node()]) { return fitSourceBorders({ image: im, slideSize: { width: im.width, height: im.height }, shapes }); }

test("fits a complete antialiased hollow source frame without mutating source data", () => { const im = image(); frame(im, 20, 16, 50, 34); pixel(im, 45, 16, [110, 175, 235]); const original = node(); const out = run(im, [original]); assert.deepEqual(out.shapes[0].box, { x: 20, y: 16, w: 50, h: 34 }); assert.notEqual(out.shapes[0], original); assert.equal(out.evidence.accepted, 1); assert.equal(im.rgba[(16 * im.width + 20) * 4], 91); });
test("does not expand a node into a connected arrow", () => { const im = image(); frame(im, 20, 16, 50, 34); for (let x = 71; x < 100; x += 1) pixel(im, x, 33, [91,163,234]); const out = run(im); assert.equal(out.shapes[0].box.w, 50); });
test("rejects blank, solid fill, endpoints, wrong color, and missing-side evidence", () => { for (const mode of ["blank", "solid", "endpoints", "wrong", "missing"]) { const im = image(); if (mode === "solid") for (let y=16;y<=50;y+=1) for(let x=20;x<=70;x+=1) pixel(im,x,y,[91,163,234]); if (mode === "endpoints") { pixel(im,20,16,[91,163,234]); pixel(im,70,50,[91,163,234]); } if (mode === "wrong") frame(im,20,16,50,34,[220,30,30]); if (mode === "missing") { frame(im,20,16,50,34); for(let x=20;x<=70;x+=1) pixel(im,x,50,[255,255,255]); } const original=node(); const out=run(im,[original]); assert.equal(out.shapes[0], original, mode); } });
test("preserves local bad shapes and non-targets while handling an empty list", () => { const im=image(); frame(im,20,16,50,34); const bad={type:"rect",box:{x:"bad"},source:{nativeComponentRole:"node",semanticNativeStructure:true}}; const other={type:"ellipse",box:{x:1,y:1,w:2,h:2}}; const out=run(im,[node(),bad,other]); assert.equal(out.shapes[1],bad); assert.equal(out.shapes[2],other); assert.deepEqual(run(im,[]).shapes,[]); });
test("rejects malformed requests and bounded resource abuse without exposing image content", () => { assert.throws(()=>fitSourceBorders(null), /Invalid source border fit request/); assert.throws(()=>fitSourceBorders({image:image(),slideSize:{width:1,height:1},shapes:{}}), /shapes/); assert.throws(()=>run({width:1,height:1,rgba:new Uint8Array(3)}), /image/); assert.throws(()=>run(image(),Array.from({length:129},node)), /Too many/); assert.throws(()=>fitSourceBorders({image:{width:16385,height:1,rgba:new Uint8Array(4)},slideSize:{width:1,height:1},shapes:[]}), /image/); });
test("fails closed for extreme boxes, transparent pixels, and discontinuous borders", () => { const im=image(); frame(im,20,16,50,34); for(let y=23;y<44;y+=2) pixel(im,20,y,[255,255,255]); const proposed=node(); const extreme=node({x:1e300,y:1,w:2,h:2}); assert.equal(run(im,[proposed]).shapes[0],proposed); assert.equal(run(im,[extreme]).shapes[0],extreme); const transparent=image(); frame(transparent,20,16,50,34); for(let x=20;x<=70;x+=1) transparent.rgba[(16*transparent.width+x)*4+3]=0; assert.equal(run(transparent).evidence.accepted,0); assert.throws(()=>fitSourceBorders({image:im,slideSize:{width:1e-320,height:1},shapes:[]}),/slide size/); });
test("bounds ordinary shape lists separately from node candidates", () => { const im=image(); const others=Array.from({length:10000},()=>({type:"ellipse"})); assert.equal(run(im,others).shapes.length,10000); assert.throws(()=>run(im,Array.from({length:129},node)),/nodes/); assert.throws(()=>run(im,Array.from({length:10001},()=>({}))),/shapes/); });
test("does not apply an axis-aligned fit to rotated or malformed rotation nodes", () => { const im=image(); frame(im,20,16,50,34); for (const rotation of [10, "0"]) { const proposed={...node(),style:{stroke:"#1473E6",rotationDeg:rotation}}; assert.equal(run(im,[proposed]).shapes[0],proposed); } });
test("enforces the aggregate sampling cap without changing inputs", () => { const im=image(1600,1200); const shapes=Array.from({length:128},()=>node({x:10,y:10,w:1580,h:1180})); const before=shapes.slice(); assert.throws(()=>run(im,shapes),/sampling limit/); assert.deepEqual(shapes,before); assert.equal(im.rgba[0],255); });
